---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidding-web
  namespace: bidding-web
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: bidding-web
  template:
    metadata:
      labels:
        app: bidding-web
        k8s-app: bidding-web
    spec:
      containers:
        - image: lamth2/bidding-web
          name: bidding-web
          imagePullPolicy: Never
          args:
            - '--spring.profiles.active=k8s'
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: bidding-web
  name: bidding-web
  namespace: bidding-web
spec:
  type: NodePort
  ports:
    - nodePort: 30020
      port: 8080
      name: web
  selector:
    k8s-app: bidding-web
